# Generated by Django 5.0.4 on 2024-06-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub_active_till',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userfavorites',
            name='is_active',
            field=models.CharField(default='A', max_length=20),
        ),
    ]
