# Generated by Django 5.0.4 on 2024-05-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorites',
            name='track',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='track',
        ),
    ]
