# Generated by Django 5.0.4 on 2024-05-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub_active_till',
            field=models.DateTimeField(null=True),
        ),
    ]
