# Generated by Django 5.0.4 on 2024-06-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_sub_active_till_userfavorites_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='otpVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14)),
                ('otp', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'otp_verify',
                'managed': True,
            },
        ),
    ]
