# Generated by Django 5.0.4 on 2024-05-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_sub_active_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavorites',
            name='is_active',
            field=models.CharField(default='A', max_length=20),
        ),
    ]
