# Generated by Django 5.0.4 on 2024-05-13 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userfavorites_track_remove_userlibrary_track'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.musictrack'),
        ),
        migrations.RemoveField(
            model_name='userfavorites',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='user',
        ),
        migrations.DeleteModel(
            name='MusicTrack',
        ),
        migrations.DeleteModel(
            name='UserFavorites',
        ),
        migrations.DeleteModel(
            name='UserLibrary',
        ),
    ]
