# Generated by Django 5.0.4 on 2024-06-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='applied_referral_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
