# Generated by Django 5.0.4 on 2024-05-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_subscription_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentmusic',
            name='status',
            field=models.CharField(default='A', max_length=50),
        ),
    ]
