# Generated by Django 5.0.4 on 2024-05-11 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_date_of_birth_alter_profile_gender'),
        ('music', '0003_alter_musicaudio_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorites',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fav_track', to='music.musicaudio'),
        ),
    ]
