# Generated by Django 5.0.4 on 2024-05-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userfavorites_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentmusic',
            old_name='track',
            new_name='music',
        ),
    ]
