# Generated by Django 5.0.4 on 2024-06-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='referral_code',
            field=models.CharField(default='hello', max_length=10),
            preserve_default=False,
        ),
    ]
