# Generated by Django 5.0.4 on 2024-06-08 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_userdetails_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='deviceLoginCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_token', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_details_device', to='user_management.userdetails')),
            ],
            options={
                'db_table': 'user_device_login',
                'managed': True,
            },
        ),
    ]
