# Generated by Django 5.0.4 on 2024-05-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_userdetails_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
