# Generated by Django 5.0.4 on 2024-06-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_devicelogincheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelogincheck',
            name='device_id',
            field=models.CharField(default='sad', max_length=255),
            preserve_default=False,
        ),
    ]
