# Generated by Django 5.0.4 on 2024-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='status',
            field=models.CharField(default='A', max_length=50),
        ),
    ]
