# Generated by Django 5.0.4 on 2024-05-13 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='image',
            field=models.FileField(null=True, upload_to='image_files/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
