# Generated by Django 5.0.4 on 2024-05-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
