# Generated by Django 5.0.4 on 2024-05-13 05:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('duration', models.DurationField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('language', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('path', models.FileField(null=True, upload_to='mp3_files/', validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('image', models.FileField(null=True, upload_to='image_files/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'music_audio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MusicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='image_files/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
            ],
            options={
                'db_table': 'music_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MusicCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_category', to='music.musiccategory')),
                ('music', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_track', to='music.musicaudio')),
            ],
            options={
                'db_table': 'music_category_mapping',
                'managed': True,
            },
        ),
    ]
