# Generated by Django 5.0.4 on 2024-05-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicaudio',
            name='path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
