# Generated by Django 5.0.4 on 2024-06-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_musiccategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicaudio',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='musicaudio',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='musicaudio',
            name='release_date',
        ),
    ]
