# Generated by Django 5.0.4 on 2024-05-11 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicaudio_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicaudio',
            name='path',
            field=models.FileField(null=True, upload_to='mp3_files/', validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
    ]
