# Generated by Django 5.0.4 on 2024-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_musicaudio_genre_musicaudio_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicaudio',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
