# Generated by Django 5.0.4 on 2024-05-12 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_musicaudio_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiccategorymapping',
            name='music',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_track', to='music.musicaudio'),
        ),
    ]
