# Generated by Django 5.0.4 on 2024-05-12 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_musiccategorymapping_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccategory',
            name='image',
            field=models.FileField(null=True, upload_to='image_files/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
